### ISSUE TITLE
Using existing dataset

### ISSUE THREAD

**Issue by mvardin** [cceyda/common-voice-explorer#3]
Hi
Thanks for your projcet
I already have the dataset and dont want to downlaoad it again ...
How can i set my dataset to explorer?

**Comment by cceyda** [comment]
You mean you already downloaded from mozilla's site right?

I'm using huggingface datasets to load data as seen [here](https://github.com/cceyda/common-voice-explorer/blob/77c96b90ea53695291e22db47669386454b3a123/common_voice.py#L33)
which returns data in [this format](https://huggingface.co/datasets/common_voice#data-instances) :

```
{'accent': 'netherlands', 'age': 'fourties', 'client_id': 'bbbcb732e0f422150c30ff3654bbab572e2a617da107bca22ff8b89ab2e4f124d03b6a92c48322862f60bd0179ae07baf0f9b4f9c4e11d581e0cec70f703ba54', 'down_votes': 0, 'gender': 'male', 'locale': 'nl', 'path': 'nl/clips/common_voice_nl_23522441.mp3', 'segment': "''", 'sentence': 'Ik vind dat een dubieuze procedure.', 'up_votes': 2}
```
which I then pass to a pandas dataframe `pd.DataFrame(dat)`.

So technically you can change the `cache_dataset` function to load your data in the same dictionary format and pass to pandas.

**Comment by mvardin** [comment]
Yes , thank you
